services:
  manager:
    build: manager
    volumes:
      - ./manager/app:/app
    command: [ "--reload", "--reload-dir", "./app" ]

  list:
    build: list

  proxy:
    environment:
      - USE_LOCAL_CA=1
